# Generated by Django 3.1 on 2021-05-01 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='currency',
            field=models.CharField(default='INR', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='rzp_payment_id',
            field=models.CharField(default='None', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='success',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
