# Generated by Django 3.1 on 2021-05-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_auto_20210501_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donor_zipcode',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
