# Generated by Django 3.1 on 2021-05-14 19:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_auto_20210515_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
