# Generated by Django 3.1 on 2021-05-14 19:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_donation_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
