# Generated by Django 3.1 on 2021-05-20 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0009_auto_20210515_0123'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('rzp_identifier_key', 'rzp_identifier_value')},
        ),
    ]
