# Generated by Django 3.1 on 2021-05-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0010_auto_20210520_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='dr_code',
            field=models.CharField(default='change', max_length=10),
            preserve_default=False,
        ),
    ]
