# Generated by Django 3.1 on 2021-05-21 20:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0011_company_dr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='source',
            field=models.CharField(choices=[('rzp_intl', 'Razorpay International'), ('rzp_dom', 'Razorpay Domestic'), ('dr', 'Direct Relief'), ('high_value', 'High Value Donor')], default='rzp_dom', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donation',
            name='currency',
            field=models.CharField(choices=[('INR', 'INR'), ('USD', 'USD')], max_length=5),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor_address',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor_country',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor_phone',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='rzp_payment_id',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='rzp_response',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
