# Generated by Django 3.1 on 2021-05-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0012_auto_20210522_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donor_country',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor_pan',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor_phone',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor_zipcode',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
